export const ROOMBOOKING_ERROR_NOT_FOUND = "Booking not found!";
export const ROOMBOOKING_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  CHECKEDIN: "CHECKED-IN",
  CHECKEDOUT: "CHECKED-OUT",
  CANCELLED: "CANCELLED",
  NOSHOW: "NO-SHOW",
};
